name: cNMF
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py310h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - comm=0.2.1=py310h06a4308_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - fastcluster=1.3.0=py310hc74f9fe_0
  - ipykernel=6.30.1=py310h06a4308_0
  - ipython=8.30.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_core=5.8.1=py310h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - openssl=1.1.1w=h7f8727e_0
  - parso=0.8.4=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_0
  - pip=25.2=pyhc872135_0
  - platformdirs=4.3.7=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=7.0.0=py310hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py310h06a4308_0
  - pygments=2.19.1=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - anndata==0.11.4
      - array-api-compat==1.12.0
      - cnmf==1.7.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.0
      - fonttools==4.59.2
      - h5py==3.14.0
      - harmonypy==0.0.10
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - legacy-api-wrap==1.4.1
      - llvmlite==0.44.0
      - matplotlib==3.10.6
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==2.2.6
      - packaging==25.0
      - palettable==3.3.3
      - pandas==2.3.2
      - patsy==1.0.1
      - pillow==11.3.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - scanpy==1.11.4
      - scikit-learn==1.7.2
      - scikit-misc==0.5.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - session-info2==0.2.1
      - six==1.17.0
      - statsmodels==0.14.5
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
prefix: /project/xuanyao/qilong/.conda/envs/cNMF
